"""sprint_2_models

Revision ID: e91d20acba9c
Revises: ca481d367022
Create Date: 2026-04-01 00:37:02.942048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'e91d20acba9c'
down_revision: Union[str, Sequence[str], None] = 'ca481d367022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('communication_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_threads_client_id'), 'communication_threads', ['client_id'], unique=False)
    op.create_index(op.f('ix_communication_threads_id'), 'communication_threads', ['id'], unique=False)
    op.create_index(op.f('ix_communication_threads_process_id'), 'communication_threads', ['process_id'], unique=False)
    op.create_index(op.f('ix_communication_threads_tenant_id'), 'communication_threads', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('external_msg_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['communication_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_task_id')
    )
    op.add_column('audit_logs', sa.Column('hash_sha256', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('hash_previous', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('geom', geoalchemy2.types.Geometry(srid=4674, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.execute("CREATE INDEX IF NOT EXISTS idx_properties_geom ON properties USING gist (geom)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_properties_geom', table_name='properties', postgresql_using='gist')
    op.drop_column('properties', 'geom')
    op.drop_column('audit_logs', 'hash_previous')
    op.drop_column('audit_logs', 'hash_sha256')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_communication_threads_tenant_id'), table_name='communication_threads')
    op.drop_index(op.f('ix_communication_threads_process_id'), table_name='communication_threads')
    op.drop_index(op.f('ix_communication_threads_id'), table_name='communication_threads')
    op.drop_index(op.f('ix_communication_threads_client_id'), table_name='communication_threads')
    op.drop_table('communication_threads')
    # ### end Alembic commands ###
